<?php
/**
 * @file
 * Plugin definition.
 */

$plugin = array(
  'title' => t('McBryan'),
  'icon' => 'mcbryanpink.png',
  'category' => t('Kalatheme'),
  'theme' => 'mcbryan',
  'css' => 'mcbryan.css',
  'regions' => array(
    'main' => t('Main'),
    'image' => t('Image'),
    'footer1' => t('Row 1: First Column'),
    'footer2' => t('Row 1: Second Column'),
    'footer3' => t('Row 1: Third Column'),
  ),
);
