<?php
/**
 * @file
 * Plugin definition.
 */

$plugin = array(
  'title' => t('Wooten'),
  'icon' => 'wootenblue.png',
  'category' => t('Kalatheme'),
  'theme' => 'wooten',
  'css' => 'wooten.css',
  'regions' => array(
    'header' => t('Header'),
    'main' => t('Main'),
    'second' => t('Second'),
    'footer1' => t('Row 1: First Column'),
    'footer2' => t('Row 1: Second Column'),
    'footer3' => t('Row 1: Third Column'),
  ),
);
