<?php
// Plugin definition
$plugin = array(
  'title' => t('Roye'),
  'icon' => 'royeblack.png',
  'category' => t('Kalatheme'),
  'theme' => 'roye',
  'css' => 'roye.css',
  'regions' => array(
    'header' => t('Header'),
    'columnhead' => t('Column Header'),
    'column1' => t('Column 1'),
    'column2' => t('Column 2'),
    'footer1' => t('Row 1: First Column'),
    'footer2' => t('Row 1: Second Column'),
    'footer3' => t('Row 1: Third Column'),
  ),
);
