<?php
// Plugin definition
$plugin = array(
  'title' => t('Ward'),
  'icon' => 'wardgold.png',
  'category' => t('Kalatheme'),
  'theme' => 'ward',
  'css' => 'ward.css',
  'regions' => array(
    'header' => t('Header'),
    'sidebar' => t('Content Sidebar'),
    'contentmain' => t('Content'),
    'footer1' => t('Row 1: First Column'),
    'footer2' => t('Row 1: Second Column'),
    'footer3' => t('Row 1: Third Column'),
  ),
);
