<?php
// Plugin definition
$plugin = array(
  'title' => t('Hastings'),
  'icon' => 'hastingsred.png',
  'category' => t('Kalatheme'),
  'theme' => 'hastings',
  'css' => 'hastings.css',
  'regions' => array(
    'header' => t('Header'),
    'main' => t('Main'),
    'footer1' => t('Row 1: First Column'),
    'footer2' => t('Row 1: Second Column'),
    'footer3' => t('Row 1: Third Column'),
  ),
);
